name = "advent_20211209"
uuid = "cafd16c4-7184-41fe-b67b-e99cdec51c46"
authors = ["alexander papageorge <atpapag@gmail.com>"]
version = "0.1.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
